import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency } from '../utils/currency';

interface ReportData {
    timeRange: string;
    currency: string;
    kpis: {
        revenue: number;
        itemsSold: number;
        turnover: number;
        accuracy: number;
    };
    quickStats: {
        activeSkus: number;
        avgOrderValue: number;
        pendingTransfers: number;
        lowStockAlerts: number;
    };
    generatedBy: string;
}

// Helper to safe format currency for PDF (avoiding unicode symbols that break jsPDF)
const formatCurrencyForPdf = (amount: number, currency: string): string => {
    // Format without symbol first
    const formattedAmount = formatCurrency(amount, currency, false);
    return `${currency} ${formattedAmount}`;
};

export const generateAnalyticsReport = (data: ReportData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;

    // -- Header --
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text('Trayvorix', margin, margin);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('Inventory Management System', margin, margin + 6);

    // Report Title
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Analytics & Performance Report', margin, margin + 20);

    // Metadata
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const dateStr = new Date().toLocaleString();
    doc.text(`Generated on: ${dateStr}`, margin, margin + 28);
    doc.text(`Time Range: ${data.timeRange}`, margin, margin + 34);
    doc.text(`Generated by: ${data.generatedBy}`, margin, margin + 40);

    // -- KPI Section --
    let yPos = margin + 55;
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Key Performance Indicators', margin, yPos);

    yPos += 10;
    const kpiWidth = (pageWidth - (margin * 2)) / 2;

    // KPI Support Function
    const drawKpiCard = (x: number, y: number, title: string, value: string, subtext: string) => {
        doc.setFillColor(248, 250, 252); // Light gray background
        doc.setDrawColor(226, 232, 240); // Border color
        doc.roundedRect(x, y, kpiWidth - 5, 30, 2, 2, 'FD');

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(title, x + 5, y + 8);

        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text(value, x + 5, y + 18);

        doc.setFontSize(8);
        doc.setTextColor(75, 85, 99);
        doc.text(subtext, x + 5, y + 25);
    };

    drawKpiCard(margin, yPos, 'Total Revenue', formatCurrencyForPdf(data.kpis.revenue, data.currency), '↑ 12.5% from last period');
    drawKpiCard(margin + kpiWidth, yPos, 'Items Sold', data.kpis.itemsSold.toLocaleString(), '↑ 8.3% from last period');

    yPos += 35;
    drawKpiCard(margin, yPos, 'Inventory Turnover', `${data.kpis.turnover}x`, '↑ 0.3x from last period');
    drawKpiCard(margin + kpiWidth, yPos, 'Stock Accuracy', `${data.kpis.accuracy}%`, '↑ 1.2% from last period');

    // -- Quick Stats Table --
    yPos += 45;
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Quick Statistics', margin, yPos);

    yPos += 5;

    const formattedAvgOrderValue = formatCurrencyForPdf(data.quickStats.avgOrderValue, data.currency);

    autoTable(doc, {
        startY: yPos,
        head: [['Metric', 'Value', 'Status']],
        body: [
            ['Active SKUs', data.quickStats.activeSkus.toLocaleString(), 'Normal'],
            ['Avg. Order Value', formattedAvgOrderValue, 'Good'],
            ['Pending Transfers', data.quickStats.pendingTransfers.toString(), 'Requires Action'],
            ['Low Stock Alerts', data.quickStats.lowStockAlerts.toString(), 'Critical'],
        ],
        theme: 'grid',
        headStyles: { fillColor: [79, 70, 229] }, // Indigo-600
        styles: { fontSize: 10 },
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
            `Page ${i} of ${pageCount}`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
        );
    }

    // Save the PDF
    const filename = `trayvorix_analytics_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(filename);
};

export const generateInventoryReport = (products: any[]) => {
    const doc = new jsPDF();
    const margin = 20;

    // Header
    doc.setFontSize(22);
    doc.text('Inventory Status Report', margin, margin);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, margin + 6);

    const tableData = products.map(p => [
        p.name,
        p.sku,
        p.category,
        p.quantity.toString(),
        formatCurrency(p.price, 'USD'), // Using default currency for now
        formatCurrency(p.price * p.quantity, 'USD'),
        p.status
    ]);

    autoTable(doc, {
        startY: margin + 15,
        head: [['Product', 'SKU', 'Category', 'Qty', 'Unit Price', 'Total Value', 'Status']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [41, 128, 185] },
        styles: { fontSize: 8 },
        columnStyles: {
            3: { halign: 'right' },
            4: { halign: 'right' },
            5: { halign: 'right' },
        }
    });

    doc.save(`inventory_report_${new Date().toISOString().split('T')[0]}.pdf`);
};

export const generateLowStockReport = (products: any[]) => {
    const doc = new jsPDF();
    const margin = 20;

    doc.setFontSize(22);
    doc.setTextColor(231, 76, 60); // Red color for urgency
    doc.text('Low Stock Alert Report', margin, margin);
    doc.setTextColor(0);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, margin + 6);

    const tableData = products.map(p => [
        p.name,
        p.sku,
        p.quantity.toString(),
        p.reorder_point?.toString() || '0',
        (p.quantity <= 0 ? 'Out of Stock' : 'Low Stock')
    ]);

    autoTable(doc, {
        startY: margin + 15,
        head: [['Product', 'SKU', 'Current Qty', 'Reorder Point', 'Status']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: [231, 76, 60] }, // Red header
        styles: { fontSize: 10 },
    });

    doc.save(`low_stock_report_${new Date().toISOString().split('T')[0]}.pdf`);
};

export const generateStockMovementsReport = (movements: any[]) => {
    const doc = new jsPDF();
    const margin = 20;

    doc.setFontSize(22);
    doc.text('Stock Movements Report', margin, margin);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, margin + 6);

    const tableData = movements.map(m => [
        new Date(m.created_at).toLocaleDateString(),
        m.type.toUpperCase(),
        m.product?.name || 'Unknown Product',
        m.quantity.toString(),
        m.reference || '-'
    ]);

    autoTable(doc, {
        startY: margin + 15,
        head: [['Date', 'Type', 'Product', 'Quantity', 'Reference']],
        body: tableData,
        theme: 'grid',
        styles: { fontSize: 9 },
    });

    doc.save(`stock_movements_${new Date().toISOString().split('T')[0]}.pdf`);
};

export interface DashboardReportData {
    totalProducts: number;
    totalInventoryValue: number;
    lowStockItems: number;
    pendingTransfers: number;
    currency: string;
}

export const generateDashboardReport = (data: DashboardReportData) => {
    const doc = new jsPDF();
    const margin = 20;

    // Header
    doc.setFontSize(22);
    doc.text('Trayvorix', margin, margin);
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('Inventory Management System', margin, margin + 6);

    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Dashboard Overview Report', margin, margin + 20);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, margin + 28);

    // KPI Cards Section (Simplified list for now)
    let yPos = margin + 45;
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Key Performance Indicators', margin, yPos);
    yPos += 10;

    const kpiData = [
        ['Total Products', data.totalProducts.toString()],
        ['Inventory Value', formatCurrencyForPdf(data.totalInventoryValue, data.currency)],
        ['Low Stock Items', data.lowStockItems.toString()],
        ['Pending Transfers', data.pendingTransfers.toString()]
    ];

    autoTable(doc, {
        startY: yPos,
        head: [['Metric', 'Value']],
        body: kpiData,
        theme: 'grid',
        headStyles: { fillColor: [63, 81, 181] }, // Indigo
        styles: { fontSize: 12, cellPadding: 3 },
    });

    doc.save(`dashboard_report_${new Date().toISOString().split('T')[0]}.pdf`);
};
