import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency } from '../utils/currency';

interface ReportData {
    timeRange: string;
    currency: string;
    kpis: {
        revenue: number;
        itemsSold: number;
        turnover: number;
        accuracy: number;
    };
    quickStats: {
        activeSkus: number;
        avgOrderValue: number;
        pendingTransfers: number;
        lowStockAlerts: number;
    };
    generatedBy: string;
}

// Helper to safe format currency for PDF (avoiding unicode symbols that break jsPDF)
const formatCurrencyForPdf = (amount: number, currency: string): string => {
    // Format without symbol first
    const formattedAmount = formatCurrency(amount, currency, false);
    return `${currency} ${formattedAmount}`;
};

export const generateAnalyticsReport = (data: ReportData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;

    // -- Header --
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text('Trayvorix', margin, margin);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('Inventory Management System', margin, margin + 6);

    // Report Title
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Analytics & Performance Report', margin, margin + 20);

    // Metadata
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const dateStr = new Date().toLocaleString();
    doc.text(`Generated on: ${dateStr}`, margin, margin + 28);
    doc.text(`Time Range: ${data.timeRange}`, margin, margin + 34);
    doc.text(`Generated by: ${data.generatedBy}`, margin, margin + 40);

    // -- KPI Section --
    let yPos = margin + 55;
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Key Performance Indicators', margin, yPos);

    yPos += 10;
    const kpiWidth = (pageWidth - (margin * 2)) / 2;

    // KPI Support Function
    const drawKpiCard = (x: number, y: number, title: string, value: string, subtext: string) => {
        doc.setFillColor(248, 250, 252); // Light gray background
        doc.setDrawColor(226, 232, 240); // Border color
        doc.roundedRect(x, y, kpiWidth - 5, 30, 2, 2, 'FD');

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(title, x + 5, y + 8);

        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text(value, x + 5, y + 18);

        doc.setFontSize(8);
        doc.setTextColor(75, 85, 99);
        doc.text(subtext, x + 5, y + 25);
    };

    drawKpiCard(margin, yPos, 'Total Revenue', formatCurrencyForPdf(data.kpis.revenue, data.currency), '↑ 12.5% from last period');
    drawKpiCard(margin + kpiWidth, yPos, 'Items Sold', data.kpis.itemsSold.toLocaleString(), '↑ 8.3% from last period');

    yPos += 35;
    drawKpiCard(margin, yPos, 'Inventory Turnover', `${data.kpis.turnover}x`, '↑ 0.3x from last period');
    drawKpiCard(margin + kpiWidth, yPos, 'Stock Accuracy', `${data.kpis.accuracy}%`, '↑ 1.2% from last period');

    // -- Quick Stats Table --
    yPos += 45;
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Quick Statistics', margin, yPos);

    yPos += 5;

    const formattedAvgOrderValue = formatCurrencyForPdf(data.quickStats.avgOrderValue, data.currency);

    autoTable(doc, {
        startY: yPos,
        head: [['Metric', 'Value', 'Status']],
        body: [
            ['Active SKUs', data.quickStats.activeSkus.toLocaleString(), 'Normal'],
            ['Avg. Order Value', formattedAvgOrderValue, 'Good'],
            ['Pending Transfers', data.quickStats.pendingTransfers.toString(), 'Requires Action'],
            ['Low Stock Alerts', data.quickStats.lowStockAlerts.toString(), 'Critical'],
        ],
        theme: 'grid',
        headStyles: { fillColor: [79, 70, 229] }, // Indigo-600
        styles: { fontSize: 10 },
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
            `Page ${i} of ${pageCount}`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
        );
    }

    // Save the PDF
    const filename = `trayvorix_report_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(filename);
};
